baseurl = "https://unoun.github.io/"
languageCode = "ja"
title = "Personal Log"
theme = "hugo-phlat-theme"

[permalinks]
    post = "/:year/:month/:slug/"
    page = "/:slug/"

[taxonomies]
    tag = "tags"
    category = "categories"

[params]
    keywords =[]
    description = ""
    google_analytics = "UA-27837645-2"
