baseurl = "https://unoun.github.io/"
languageCode = "ja"
title = "Personal Log"
theme = "hugo-phlat-theme"
hasCJKLanguage = true

[permalinks]
    post = "/:year/:month/:slug/"
    page = "/:slug/"

[taxonomies]
    tag = "tags"
    category = "categories"

[params]
    keywords =[]
    description = "気になる情報や、空想などを書いていこうと思います。"
    google_analytics = "UA-27837645-2"
